version: 2.1

jobs:
  secret-scan:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install Gitleaks (v8.18.2)
          command: |
            curl -sSL -o gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
            tar -xvzf gitleaks.tar.gz
            chmod +x gitleaks
            sudo mv gitleaks /usr/local/bin/
      - run:
          name: Run Gitleaks secret scan
          command: gitleaks detect --source . --config .gitleaks.toml --no-git


  dependency-audit:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install pip-audit and dependencies
          command: |
            python -m pip install --upgrade pip
            pip install pip-audit
            pip install -r requirements.txt
      - run:
          name: Run pip-audit
          command: pip-audit

workflows:
  version: 2
  run-security-checks:
    jobs:
      - secret-scan
      - dependency-audit